CREATE TABLE BATTLE 
(
  ID NUMBER NOT NULL 
, HUMANS NUMBER 
, TROLLS NUMBER 
, WINNER VARCHAR2(20) 
, CONSTRAINT BATTLE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE BATTLE_SEQ;

CREATE TRIGGER BATTLE_TRG 
BEFORE INSERT ON BATTLE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT BATTLE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TABLE BATTLE_LOG 
(
  ID NUMBER NOT NULL 
, BATTLE_ID NUMBER 
, ROUND NUMBER 
, HUMAN_HEALTH NUMBER 
, TROLL_HEALTH NUMBER 
, ATTACKER VARCHAR2(20) 
, HUMAN_ARMY VARCHAR2(20) 
, TROLL_ARMY VARCHAR2(20) 
, CONSTRAINT BATTLE_LOG_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE BATTLE_LOG
ADD CONSTRAINT BATTLE_LOG_FK1 FOREIGN KEY
(
  BATTLE_ID 
)
REFERENCES BATTLE
(
  ID 
)
ENABLE;

CREATE SEQUENCE BATTLE_LOG_SEQ;

CREATE TRIGGER BATTLE_LOG_TRG 
BEFORE INSERT ON BATTLE_LOG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT BATTLE_LOG_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
